"""Add model_url to Product

Revision ID: 1505c2f2cf22
Revises: ea764542d826
Create Date: 2025-04-28 08:00:50.341910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1505c2f2cf22'
down_revision = 'ea764542d826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('model_3d_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_3d_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('model_url')

    # ### end Alembic commands ###
