"""Add model_url to Product

Revision ID: 5653d0a4dcde
Revises: bfdc7f440439
Create Date: 2025-04-28 17:34:16.528879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5653d0a4dcde'
down_revision = 'bfdc7f440439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
