"""add status field to order

Revision ID: 5b09789989b2
Revises: 5653d0a4dcde
Create Date: 2025-04-28 17:40:54.163714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b09789989b2'
down_revision = '5653d0a4dcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('total')

    # ### end Alembic commands ###
