"""Add image_url to products

Revision ID: 616ab0345e2b
Revises: a32722516787
Create Date: 2025-04-21 04:30:53.105293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616ab0345e2b'
down_revision = 'a32722516787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
