"""Ajout de la colonne model_url

Revision ID: 649508b4b978
Revises: 686dd4b54cb3
Create Date: 2025-04-22 04:28:37.754978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649508b4b978'
down_revision = '686dd4b54cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('model_url')

    # ### end Alembic commands ###
